import { detectQuality, type Quality } from '../core/quality';
import { DEFAULT_SEED, type Vec2 } from '../core/types';
import { CameraRig } from '../camera/CameraRig';
import { Controls } from '../input/Controls';
import { Input } from '../input/Input';
import { EntityViews } from '../render/EntityViews';
import { FogOfWar } from '../render/fog';
import { GrassField } from '../render/Grass';
import { PropsView } from '../render/PropsView';
import { Renderer } from '../render/Renderer';
import { TerrainView } from '../render/TerrainView';
import { BALANCE } from '../sim/balance';
import { generateMap } from '../sim/mapgen';
import { World } from '../sim/World';
import { Hud } from '../ui/Hud';
import { Minimap } from '../ui/Minimap';
import { Selection } from './Selection';

const STEP = 1 / BALANCE.tickRate;
const MAX_STEPS_PER_FRAME = 3;

/**
 * Composition root and main loop: fixed-step sim, interpolated rendering.
 * Owned by the integrator — lanes do not edit this file.
 */
export class Game {
  readonly world: World;
  readonly renderer: Renderer;
  readonly rig: CameraRig;
  readonly selection = new Selection();
  readonly quality: Quality;
  private readonly input: Input;
  private readonly terrain: TerrainView;
  private readonly views: EntityViews;
  private readonly props: PropsView;
  private readonly grass: GrassField;
  private readonly fog: FogOfWar;
  private readonly controls: Controls;
  private readonly hud: Hud;
  private readonly minimap: Minimap;
  private accumulator = 0;
  private last = performance.now();
  private elapsed = 0;
  private raf = 0;
  private readonly onResize = () => this.resize();

  constructor(private readonly container: HTMLElement, seed = DEFAULT_SEED) {
    const { hf, layout } = generateMap(seed);
    this.world = new World(hf, layout);

    this.quality = detectQuality();
    this.renderer = new Renderer(container, this.quality);
    this.input = new Input(this.renderer.domElement);
    this.rig = new CameraRig(hf, this.input, layout.townCenter);

    this.terrain = new TerrainView(hf, this.quality);
    this.views = new EntityViews(this.world);
    this.props = new PropsView(hf, layout.props);
    this.grass = new GrassField(hf, this.quality);
    this.fog = new FogOfWar(this.world.visibility, this.quality);
    this.terrain.setFog(this.fog);
    this.props.setFog(this.fog);
    this.grass.setFog(this.fog);
    this.views.setFog(this.fog);
    this.views.setShadows(this.quality.shadows);
    this.props.setShadows(this.quality.shadows);
    this.renderer.scene.add(this.terrain.object, this.props.object, this.grass.object, this.views.object);

    this.selection.onChange((ids) => this.views.setSelected(ids));
    this.controls = new Controls({
      world: this.world,
      views: this.views,
      rig: this.rig,
      input: this.input,
      selection: this.selection,
      canvas: this.renderer.domElement,
      hud: document.getElementById('hud') ?? container,
      props: layout.props,
    });
    this.hud = new Hud(this.world, this.selection, () => this.train());
    this.minimap = new Minimap(document.getElementById('hud') ?? container, this.world, this.rig);

    window.addEventListener('resize', this.onResize);
    this.resize();
    this.raf = requestAnimationFrame(this.frame);
  }

  train(): void {
    this.world.dispatch({ type: 'train', buildingId: this.world.townCenter.id });
  }

  private frame = (now: number) => {
    const dt = Math.min((now - this.last) / 1000, 0.25);
    this.last = now;
    this.elapsed += dt;

    this.controls.update(dt);
    this.rig.update(dt);

    this.accumulator += dt;
    let steps = 0;
    while (this.accumulator >= STEP && steps < MAX_STEPS_PER_FRAME) {
      this.world.tick(STEP);
      this.accumulator -= STEP;
      steps++;
    }
    if (steps === MAX_STEPS_PER_FRAME) this.accumulator = 0;

    this.fog.update(dt);
    this.props.syncFog();
    const focus = this.focus();
    this.renderer.update(focus, this.elapsed);
    this.terrain.update(this.elapsed);
    this.grass.update(focus, this.elapsed);
    this.views.sync(this.accumulator / STEP, this.elapsed, this.rig.camera);
    this.hud.update();
    this.minimap.update(this.elapsed);
    this.renderer.render(this.rig.camera);
    this.input.endFrame();
    this.raf = requestAnimationFrame(this.frame);
  };

  /** Ground point the player is looking at: shadows, grass and sky follow it. */
  private focus(): Vec2 {
    const p = this.rig.mode === 'fps' ? this.rig.fps.pos : this.rig.rts.target;
    return { x: p.x, z: p.z };
  }

  private resize(): void {
    const w = this.container.clientWidth || window.innerWidth;
    const h = this.container.clientHeight || window.innerHeight;
    this.renderer.setSize(w, h);
    this.rig.setAspect(w / h);
  }

  dispose(): void {
    cancelAnimationFrame(this.raf);
    window.removeEventListener('resize', this.onResize);
    this.input.dispose();
    this.minimap.dispose();
    this.props.dispose();
    this.renderer.domElement.remove();
  }
}
