import { deviceQuality, type Quality } from '../core/quality';
import type { EntityId, Vec2 } from '../core/types';
import { CameraRig } from '../camera/CameraRig';
import { yawBasis } from '../camera/FpsCamera';
import { MAX_DISTANCE, MIN_DISTANCE } from '../camera/RtsCamera';
import { Controls } from '../input/Controls';
import { Input } from '../input/Input';
import { EntityViews } from '../render/EntityViews';
import { FogOfWar } from '../render/fog';
import { GrassField } from '../render/Grass';
import { PropsView } from '../render/PropsView';
import { Renderer } from '../render/Renderer';
import { TerrainView } from '../render/TerrainView';
import { BALANCE } from '../sim/balance';
import { generateMap } from '../sim/mapgen';
import { deserializeWorld, serializeWorld } from '../sim/serialize';
import { World } from '../sim/World';
import { Endgame } from '../ui/Endgame';
import { EndgameLog } from '../ui/endgameLog';
import { Hud } from '../ui/Hud';
import { Minimap } from '../ui/Minimap';
import {
  AUTOSAVE_MS,
  RESUME_KEY,
  RESUME_VERSION,
  deleteResume,
  downloadResume,
  idbResumeStore,
  readResume,
  readResumeFile,
  type ResumeEnvelope,
  type ResumeStore,
} from './resume';
import { audioBus } from './audioBus';
import { MatchAudio } from './sfxDirector';
import { matchPlayers, matchSeed } from './matchSetup';
import { isGameSpeed, simScale, type GameSpeed } from './pace';
import { Selection } from './Selection';
import { TutorialCoach } from './tutorialCoach';
import { closeSettings, settingsOpen } from './settingsPanel';
import {
  bootQuality,
  currentSettings,
  ensureSettings,
  paintPlayerColors,
  subscribeSettings,
  type Settings,
} from './settings';

const STEP = 1 / BALANCE.tickRate;
const MAX_STEPS_PER_FRAME = 3;

/** How a match is opened. A resume wins unless `fresh` is set. */
export interface MatchStart {
  seed?: number;
  players?: number;
  fresh?: boolean;
  /** Practice match. It does not read or write the resume slot. */
  tutorial?: boolean;
}

/** Milliseconds spent in each boot stage. `totalMs` ends when the first frame is scheduled. */
export interface BootTimings {
  mapMs: number;
  terrainMs: number;
  modelsMs: number;
  totalMs: number;
}

export type BootReport = (label: string, fraction: number) => void;

/** Let the browser paint the loading screen before the next blocking stage. */
function afterPaint(): Promise<void> {
  return new Promise((resolve) => {
    requestAnimationFrame(() => requestAnimationFrame(() => resolve()));
  });
}

interface BootParts {
  layout: ReturnType<typeof generateMap>['layout'];
  world: World;
  quality: Quality;
  renderer: Renderer;
  input: Input;
  rig: CameraRig;
  terrain: TerrainView;
  views: EntityViews;
  props: PropsView;
  grass: GrassField;
  fog: FogOfWar;
  boot: BootTimings;
  store: ResumeStore;
  resume: ResumeEnvelope | null;
  resumeFailed: boolean;
  tutorial: boolean;
}

/**
 * Composition root and main loop: fixed-step sim, interpolated rendering.
 * Owned by the integrator — lanes do not edit this file.
 */
export class Game {
  readonly world: World;
  readonly renderer: Renderer;
  readonly rig: CameraRig;
  readonly selection = new Selection();
  readonly quality: Quality;
  readonly boot: BootTimings;
  private readonly input: Input;
  private readonly terrain: TerrainView;
  private readonly views: EntityViews;
  private readonly props: PropsView;
  private readonly grass: GrassField;
  private readonly fog: FogOfWar;
  private readonly controls: Controls;
  private readonly hud: Hud;
  private readonly minimap: Minimap;
  private readonly endgameLog = new EndgameLog();
  private readonly endgame: Endgame;
  /** Set when gameOver fires; the loop stops so the summary matches the last sample. */
  private matchOver = false;
  /** Pause menu. The sim clock waits; rendering continues so the menu stays live. */
  private paused = false;
  private speed: GameSpeed = 1;
  private accumulator = 0;
  private last = 0;
  private elapsed = 0;
  private raf = 0;
  private readonly store: ResumeStore;
  private readonly resume: ResumeEnvelope | null;
  /** Sim time last written, so a quiet tab does not save the same tick twice. */
  private savedSimTime = -1;
  private lastSaveWall = 0;
  private saveChain: Promise<void> = Promise.resolve();
  /** New match and Open file reload; further saves must not recreate the slot. */
  private leaving = false;
  /** Pixel-ratio cap chosen at boot. A later change waits for the next match. */
  private pixelCap = 1;
  private unsubscribeSettings: () => void = () => {};
  /** Practice match. Saves must not replace the resume slot. */
  private tutorial = false;
  private tutorialCoach: TutorialCoach | null = null;
  private readonly matchAudio: MatchAudio;
  private noteTimer = 0;
  private readonly onResize = () => this.resize();
  private readonly onHide = () => {
    if (document.visibilityState === 'hidden' && this.world.time !== this.savedSimTime) this.remember('quiet');
  };

  /**
   * Build the world in stages so a loading screen can paint between them.
   * Map generation stays on the main thread: the heightfield is not worker-safe.
   */
  static async start(container: HTMLElement, report: BootReport = () => {}, start: MatchStart = {}): Promise<Game> {
    const t0 = performance.now();
    report('Shaping the terrain', 0.16);
    await afterPaint();

    const tMap = performance.now();
    const store = idbResumeStore();
    const loaded = await readResume(store);
    const seed = matchSeed(start.seed);
    const towns = matchPlayers(start.players);
    const tutorial = start.tutorial === true;
    let resume = start.fresh || tutorial ? null : loaded.envelope;
    let resumeFailed = start.fresh || tutorial ? false : loaded.failed;
    let mapSeed = resume?.sim.seed ?? seed;
    let players = resume?.sim.playerCount ?? towns;
    let generated: ReturnType<typeof generateMap>;
    try {
      generated = generateMap(mapSeed, players);
    } catch {
      resume = null;
      resumeFailed = true;
      mapSeed = seed;
      players = 2;
      generated = generateMap(seed);
    }
    const { hf, layout } = generated;
    let world: World;
    if (resume) {
      try {
        // deserializeWorld regenerates the same seed so scenery matches this heightfield.
        world = deserializeWorld(resume.sim, hf);
      } catch {
        resume = null;
        resumeFailed = true;
        world = new World(hf, layout);
        world.seed = mapSeed;
      }
    } else {
      world = new World(hf, layout);
      world.seed = mapSeed;
    }
    const mapMs = performance.now() - tMap;

    report('Baking the ground', 0.46);
    await afterPaint();
    const tTerrain = performance.now();
    const settings = ensureSettings();
    paintPlayerColors(
      [...world.players.values()].map((state) => state.player),
      settings.colorblind,
    );
    const quality = bootQuality(settings, deviceQuality(), typeof location === 'undefined' ? '' : location.search);
    const renderer = new Renderer(container, quality);
    const input = new Input(renderer.domElement);
    const aim = resume?.view ?? layout.townCenter;
    const rig = new CameraRig(hf, input, { x: aim.x, z: aim.z });
    if (resume) {
      rig.rts.distance = Math.min(MAX_DISTANCE, Math.max(MIN_DISTANCE, resume.view.distance));
      rig.rts.settle();
    }
    const terrain = new TerrainView(hf, quality);
    const terrainMs = performance.now() - tTerrain;

    report('Raising the models', 0.74);
    await afterPaint();
    const tModels = performance.now();
    const views = new EntityViews(world);
    const props = new PropsView(hf, layout.props);
    const grass = new GrassField(hf, quality);
    const fog = new FogOfWar(world.visibility, quality);
    const modelsMs = performance.now() - tModels;

    report('Opening the gates', 0.92);
    await afterPaint();
    const game = new Game(container, {
      layout, world, quality, renderer, input, rig, terrain, views, props, grass, fog,
      boot: { mapMs, terrainMs, modelsMs, totalMs: performance.now() - t0 },
      store, resume, resumeFailed, tutorial,
    });
    report('The city stands', 1);
    return game;
  }

  private constructor(private readonly container: HTMLElement, parts: BootParts) {
    const { layout } = parts;
    this.world = parts.world;
    this.matchAudio = new MatchAudio(this.world);
    this.quality = parts.quality;
    this.renderer = parts.renderer;
    this.input = parts.input;
    this.rig = parts.rig;
    this.terrain = parts.terrain;
    this.views = parts.views;
    this.props = parts.props;
    this.grass = parts.grass;
    this.fog = parts.fog;
    this.boot = parts.boot;
    this.store = parts.store;
    this.resume = parts.resume;
    this.savedSimTime = parts.world.time;
    this.lastSaveWall = performance.now();

    this.terrain.setFog(this.fog);
    this.props.setFog(this.fog);
    this.grass.setFog(this.fog);
    this.views.setFog(this.fog);
    this.views.setShadows(this.quality.shadows);
    this.props.setShadows(this.quality.shadows);
    this.renderer.scene.add(this.terrain.object, this.props.object, this.grass.object, this.views.object);

    this.selection.onChange((ids) => this.views.setSelected(ids));
    this.controls = new Controls({
      world: this.world,
      views: this.views,
      rig: this.rig,
      input: this.input,
      selection: this.selection,
      canvas: this.renderer.domElement,
      hud: document.getElementById('hud') ?? container,
      props: layout.props,
    });
    this.hud = new Hud(this.world, this.selection, () => this.train());
    this.minimap = new Minimap(document.getElementById('hud') ?? container, this.world, this.rig);
    this.endgame = new Endgame(this.world, this.endgameLog, () => {
      this.matchOver = true;
      this.setPaused(false);
      this.remember('quiet');
    }, () => {
      void this.leave();
    });
    if (this.resume) this.applyResume(this.resume);
    if (this.world.gameOver) this.endgame.showFinished();
    this.bindResume(parts.resumeFailed);
    this.bindPause();
    this.pixelCap = parts.quality.pixelRatio;
    this.applySettings(ensureSettings(), true);
    this.unsubscribeSettings = subscribeSettings((settings) => this.applySettings(settings, false));
    this.tutorial = parts.tutorial;
    if (parts.tutorial) this.tutorialCoach = new TutorialCoach(this.world);

    window.addEventListener('resize', this.onResize);
    document.addEventListener('visibilitychange', this.onHide);
    this.resize();
    this.last = performance.now();
    this.raf = requestAnimationFrame(this.frame);
  }

  train(): void {
    const tc = this.world.townCenter;
    if (tc) this.world.dispatch({ type: 'train', buildingId: tc.id });
  }

  private frame = (now: number) => {
    const dt = Math.min((now - this.last) / 1000, 0.25);
    this.last = now;
    this.elapsed += dt;

    this.controls.update(this.matchOver || this.paused ? 0 : dt);
    // Camera keys stay out of the pause menu. The current view still renders below.
    if (!this.matchOver && !this.paused) this.rig.update(dt);
    this.maybePauseKey();
    this.matchAudio.setEar(this.earPose());

    if (!this.matchOver && !this.paused) {
      this.accumulator += dt * simScale(this.speed, this.paused, this.matchOver);
      let steps = 0;
      while (this.accumulator >= STEP && steps < MAX_STEPS_PER_FRAME && !this.matchOver) {
        this.world.tick(STEP);
        this.accumulator -= STEP;
        steps++;
      }
      if (steps === MAX_STEPS_PER_FRAME) this.accumulator = 0;
      if (steps > 0 && now - this.lastSaveWall >= AUTOSAVE_MS && this.world.time !== this.savedSimTime) this.remember('quiet');
      // One economy sample about every 10 sim seconds. gameOver records the last one itself.
      if (!this.matchOver && this.endgameLog.shouldSample(this.world.time)) this.endgame.sample();
    }
    this.matchAudio.pulse(this.earSamples(), !this.matchOver && !this.paused, dt);

    this.fog.update(dt);
    this.props.syncFog();
    this.props.update(this.rig.camera);
    const focus = this.focus();
    const decor = currentSettings().reducedMotion ? 0 : this.elapsed;
    this.renderer.update(focus, decor);
    this.terrain.update(decor);
    if (this.grass.object.visible) this.grass.update(focus, decor);
    this.views.sync(this.accumulator / STEP, this.elapsed, this.rig.camera);
    this.hud.update();
    this.minimap.update(this.elapsed);
    this.renderer.render(this.rig.camera);
    this.input.endFrame();
    if (!this.matchOver) this.raf = requestAnimationFrame(this.frame);
  };

  /** Camera position and the ground-right axis, so voices pan with the view. */
  private earPose(): { at: Vec2; right: Vec2 } {
    if (this.rig.mode === 'fps') {
      return { at: { x: this.rig.fps.pos.x, z: this.rig.fps.pos.z }, right: yawBasis(this.rig.fps.yaw).right };
    }
    return {
      at: {
        x: this.rig.rts.target.x,
        z: this.rig.rts.target.z + Math.cos(this.rig.rts.pitch) * this.rig.rts.distance,
      },
      right: { x: 1, z: 0 },
    };
  }

  /** Points the ambience beds sample: the focus and the ground under the view. */
  private earSamples(): Vec2[] {
    if (this.rig.mode === 'fps') {
      const pos = this.rig.fps.pos;
      return [
        pos,
        { x: pos.x + 8, z: pos.z },
        { x: pos.x - 8, z: pos.z },
        { x: pos.x, z: pos.z + 8 },
        { x: pos.x, z: pos.z - 8 },
      ];
    }
    return [this.focus(), ...this.rig.viewFootprint()];
  }

  /** Ground point the player is looking at: shadows, grass and sky follow it. */
  private focus(): Vec2 {
    const p = this.rig.mode === 'fps' ? this.rig.fps.pos : this.rig.rts.target;
    return { x: p.x, z: p.z };
  }

  private resize(): void {
    const w = this.container.clientWidth || window.innerWidth;
    const h = this.container.clientHeight || window.innerHeight;
    this.renderer.setSize(w, h);
    this.rig.setAspect(w / h);
  }

  private alive(id: EntityId): boolean {
    return this.world.units.has(id) || this.world.buildings.has(id);
  }

  /** Groups, selection, and charts. The camera was already aimed in start. */
  private applyResume(resume: ResumeEnvelope): void {
    this.controls.groups.restore(resume.groups, (id) => this.alive(id));
    this.selection.set(resume.selection.filter((id) => this.alive(id)));
    this.endgameLog.replace(resume.charts);
  }

  private capture(): ResumeEnvelope {
    return {
      version: RESUME_VERSION,
      sim: serializeWorld(this.world),
      view: { x: this.rig.rts.target.x, z: this.rig.rts.target.z, distance: this.rig.rts.distance },
      groups: this.controls.groups.snapshot(),
      selection: [...this.selection.ids],
      charts: this.endgameLog.samples.map((sample) => ({ ...sample })),
      savedAt: Date.now(),
    };
  }

  /**
   * Queue a slot write. A previous failure must not skip this one, and a failure here
   * must not skip the next. Save copy still downloads when the slot cannot be written.
   */
  private remember(kind: 'quiet' | 'noted'): void {
    if (this.leaving || this.tutorial) return;
    let envelope: ResumeEnvelope;
    try {
      envelope = this.capture();
    } catch {
      this.note('Could not save the resume.');
      return;
    }
    this.savedSimTime = envelope.sim.time;
    this.lastSaveWall = performance.now();
    // Download in this turn so the browser still counts the button press as the user gesture.
    if (kind === 'noted') downloadResume(envelope);
    this.saveChain = this.saveChain
      .catch(() => undefined)
      .then(() => this.store.put(RESUME_KEY, envelope))
      .then(() => {
        if (kind === 'noted') this.note('Saved');
      })
      .catch(() => {
        this.savedSimTime = -1;
        this.note('Could not save the resume.');
      });
  }

  /** A file replaces the slot only after it parses. A bad version leaves the slot alone. */
  private async openFile(file: Blob): Promise<void> {
    let envelope: ResumeEnvelope;
    try {
      envelope = await readResumeFile(file);
    } catch (err) {
      const message = err instanceof Error ? err.message : '';
      this.note(message.startsWith('Unsupported save version') ? message : 'That file could not be opened.');
      return;
    }
    if (this.leaving) return;
    this.leaving = true;
    try {
      await this.saveChain;
      await this.store.put(RESUME_KEY, envelope);
      location.reload();
    } catch {
      this.leaving = false;
      this.note('That file could not be opened.');
    }
  }

  /** Drop the slot after any in-flight write, then reload into a new match. */
  private async leave(): Promise<void> {
    if (this.leaving) return;
    if (this.tutorial) {
      location.reload();
      return;
    }
    this.leaving = true;
    try {
      await this.saveChain;
      await deleteResume(this.store);
    } catch {
      // Reload even when the slot cannot be deleted. The next boot starts fresh if it is gone.
    }
    location.reload();
  }

  private note(text: string): void {
    const el = document.getElementById('save-note');
    if (!el) return;
    el.hidden = false;
    el.textContent = text;
    window.clearTimeout(this.noteTimer);
    this.noteTimer = window.setTimeout(() => {
      el.hidden = true;
    }, 8000);
  }

  /** Esc toggles pause unless help, placement, targeting, or the new-match confirm used it. */
  private maybePauseKey(): void {
    if (this.matchOver || !this.input.keyPressed('Escape') || this.controls.escapeUsed) return;
    if (settingsOpen()) {
      closeSettings();
      return;
    }
    const ask = document.getElementById('new-match-ask');
    if (ask && !ask.hidden) {
      ask.hidden = true;
      return;
    }
    this.setPaused(!this.paused);
  }

  private setPaused(on: boolean): void {
    if (on && this.matchOver) return;
    this.paused = on;
    this.controls.hold(on);
    const menu = document.getElementById('pause-menu');
    if (menu) menu.hidden = !on;
    const btn = document.getElementById('pause-match');
    if (btn) {
      btn.textContent = on ? 'Resume' : 'Pause';
      btn.setAttribute('aria-pressed', on ? 'true' : 'false');
    }
    if (on) document.getElementById('pause-resume')?.focus();
  }

  private setSpeed(speed: GameSpeed): void {
    this.speed = speed;
    for (const btn of document.querySelectorAll<HTMLButtonElement>('#pause-menu [data-speed]')) {
      btn.setAttribute('aria-pressed', Number(btn.dataset.speed) === speed ? 'true' : 'false');
    }
  }

  private bindPause(): void {
    document.getElementById('pause-match')?.addEventListener('click', () => this.setPaused(!this.paused));
    document.getElementById('pause-resume')?.addEventListener('click', () => this.setPaused(false));
    document.getElementById('pause-menu')?.addEventListener('click', (event) => {
      const btn = (event.target as Element).closest<HTMLButtonElement>('[data-speed]');
      if (!btn) return;
      const speed = Number(btn.dataset.speed);
      if (isGameSpeed(speed)) this.setSpeed(speed);
    });
  }

  private bindResume(failed: boolean): void {
    const input = document.getElementById('open-file-input') as HTMLInputElement | null;
    const ask = document.getElementById('new-match-ask');
    document.getElementById('save-copy')?.addEventListener('click', () => this.remember('noted'));
    document.getElementById('open-file')?.addEventListener('click', () => input?.click());
    input?.addEventListener('change', () => {
      const file = input.files?.[0];
      input.value = '';
      if (file) void this.openFile(file);
    });
    document.getElementById('new-match')?.addEventListener('click', () => {
      if (!ask) return;
      ask.hidden = false;
      document.getElementById('new-match-yes')?.focus();
    });
    document.getElementById('new-match-no')?.addEventListener('click', () => {
      if (ask) ask.hidden = true;
    });
    document.getElementById('new-match-yes')?.addEventListener('click', () => {
      void this.leave();
    });
    if (failed) this.note('The resume could not be read.');
  }

  private applySettings(settings: Settings, boot: boolean): void {
    this.rig.rts.edgeScroll = settings.edgeScroll;
    this.rig.rts.edgeSpeed = settings.edgeSpeed;
    this.rig.rts.invertPan = settings.invertPan;
    audioBus.setVolumes({ master: settings.master, music: settings.music, sfx: settings.sfx });
    this.renderer.setShadows(settings.shadows);
    this.views.setShadows(settings.shadows);
    this.props.setShadows(settings.shadows);
    const grassOk = this.grass.setShown(settings.grass);
    const water = this.terrain.setFancyWater(settings.water);
    paintPlayerColors(
      [...this.world.players.values()].map((state) => state.player),
      settings.colorblind,
    );
    this.minimap.setLocalFromPlayer(settings.colorblind);
    if (boot) return;
    const notes: string[] = [];
    if (settings.grass && !grassOk) notes.push('Grass fills in on the next match.');
    if (settings.water && water === 'next') notes.push('Detailed water starts on the next match.');
    const wanted = bootQuality(settings, deviceQuality(), typeof location === 'undefined' ? '' : location.search);
    if (wanted.pixelRatio !== this.pixelCap) notes.push('Pixel density applies on the next match.');
    if (settings.colorblind) notes.push('New units use these colours. Units already in the match keep their dye.');
    const note = document.getElementById('settings-note');
    if (note) {
      note.hidden = notes.length === 0;
      note.textContent = notes.join(' ');
    }
  }

  dispose(): void {
    this.matchAudio.dispose();
    this.tutorialCoach?.dispose();
    this.unsubscribeSettings();
    cancelAnimationFrame(this.raf);
    window.clearTimeout(this.noteTimer);
    this.endgame.dispose();
    window.removeEventListener('resize', this.onResize);
    document.removeEventListener('visibilitychange', this.onHide);
    this.input.dispose();
    this.minimap.dispose();
    this.props.dispose();
    this.renderer.domElement.remove();
  }
}
